"""The ambient sweep. One process per tick; the gate IS the job.

Three stages, no agent session anywhere:

    1. detect  — deterministic SQL prefilter          (aw_detectors, 0 tokens)
    2. judge   — ONE bounded LLM call, spend-gated    (aw_judge + aw_budget)
    3. deliver — post into the exact thread_ts        (aw_post)

WHY NO AGENT. Two facts from the real source make the original design
("a cron agent session calls send_message into the candidate's thread")
impossible, not merely awkward:

* cron/scheduler.py:182 hardcodes ``disabled = ["cronjob", "messaging",
  "clarify", "memory"]`` for every cron session, and user config layers on
  top — so ``send_message`` is unavailable in any cron agent, ever.
* ``--deliver`` is one static target per job, so it cannot address a
  per-candidate ``thread_ts``.

Running as a ``--no-agent`` job turns both constraints into non-issues
(cron/scheduler.py:3213 short-circuits before ``run_agent`` is even
imported) and wins the containment argument outright: the untrusted thread
text now exists only in this process's memory and in ``ambient.db``, which
is already jailed. It never becomes an agent prompt, so it never becomes an
FTS-indexed ``messages`` row in Hermes' shared ``state.db`` — the exact
channel the 2026-08-11 incident used. That retires the leak class instead of
mitigating it.

STDOUT CONTRACT (cron/scheduler.py:3279-3313, verified):
* last non-empty line ``{"wakeAgent": false}``  -> SILENT, stdout discarded
* any other non-empty stdout                    -> delivered verbatim to
  ``--deliver slack:<ops channel>``

So the gate ends with the false gate whenever there is nothing an operator
needs to see, and ends with an audit line when there is. The audit lines are
EXCERPT-FREE: ``_run_job_script`` pipes stdout through
``redact_sensitive_text`` and ``save_job_output`` then persists the whole
document under ``~/.hermes/cron/output/<job_id>/``, which the L3 jail does
not cover. Keeping verbatim channel text out of it is what makes that
persistence a non-issue rather than a new leak. Model-authored nudges do
appear — in live mode they were posted publicly anyway, and in shadow mode
reviewing them is the entire point of the soak.

FAIL CLOSED, EVERYWHERE. Any error prints ``{"wakeAgent": false}`` and exits
0 (a non-zero exit is delivered as a script-failure alert), and every
fail-closed path leaves a breadcrumb in
``plugin-data/ambient_watch/gate_errors.log`` — the scheduler discards a
silent run's stdout, so without the log a permanently broken gate looks
exactly like a quiet week.

CLI:
    python gate.py            # one sweep (invoked via the scripts shim)
    python gate.py --kill on  # flip kill switch (also: off)
"""

from __future__ import annotations

import json
import os
import sys
import time
import traceback
from pathlib import Path

ERROR_LOG_NAME = "gate_errors.log"
ERROR_LOG_MAX_BYTES = 64 * 1024  # rotate to .1 past this, so it can never grow

WAKE_FALSE = json.dumps({"wakeAgent": False})

# On-disk artifacts that ever held verbatim channel text. Deleted on every
# gate run and at plugin registration; nothing recreates them.
UNTRUSTED_ARTIFACTS = ("candidates.json", "candidates.json.tmp")

_SHIM_HEADER = "# auto-generated by ambient-watch install_gate(); do not edit\n"

# The shim runs OUTSIDE this package (it sys.path-inserts the plugin dir and
# imports ``gate`` flat), so it cannot call back into gate.py for its own
# breadcrumb — the import is exactly what may have failed. Its logging is
# therefore duplicated inline, in stdlib-only terms. __PLUGIN_DIR__ is
# substituted with repr(plugin_dir) at install time.
_SHIM_BODY = '''\
import os
import sys

sys.path.insert(0, __PLUGIN_DIR__)


def _breadcrumb(detail):
    """Leave a trace of a fatal shim error; never raise, never touch stdout.

    Without this a permanently broken gate is silent: the scheduler drops
    the stdout of a wakeAgent=false run, so ambient mode would simply go
    quiet with nothing anywhere to explain why.
    """
    try:
        sys.stderr.write(detail)
    except Exception:
        pass
    try:
        import time
        home = os.environ.get("HERMES_HOME")
        if not home:
            if os.name == "nt":
                home = os.path.join(
                    os.environ.get("LOCALAPPDATA") or os.path.expanduser("~"),
                    "hermes",
                )
            else:
                home = os.path.join(os.path.expanduser("~"), ".hermes")
        folder = os.path.join(home, "plugin-data", "ambient_watch")
        os.makedirs(folder, exist_ok=True)
        path = os.path.join(folder, "gate_errors.log")
        try:
            if os.path.getsize(path) > 65536:
                os.replace(path, path + ".1")
        except OSError:
            pass
        stamp = time.strftime("%Y-%m-%dT%H:%M:%S")
        with open(path, "a", encoding="utf-8") as handle:
            handle.write("[" + stamp + "] shim: " + detail.strip() + "\\n")
    except Exception:
        pass


try:
    from gate import main
    sys.exit(main(sys.argv[1:]))
except SystemExit:
    raise
except Exception:
    # Fail closed: a broken gate must never wake the agent.
    import traceback
    _breadcrumb(traceback.format_exc())
    print('{"wakeAgent": false}')
    sys.exit(0)
'''


def _hermes_home() -> Path:
    try:
        # Real loader: this file is hermes_plugins.<slug>.gate — the plugin
        # directory is NOT on sys.path, so only the relative import works.
        from .aw_config import hermes_home as _home
    except ImportError:
        # Cron shim: gate.py is imported flat after sys.path.insert(plugin_dir).
        from aw_config import hermes_home as _home
    return _home()


def record_gate_error(detail: str, data_dir=None) -> Path | None:
    """Append a fail-closed breadcrumb to ``gate_errors.log``. Best effort.

    Returns the log path, or None if the breadcrumb could not be written —
    this must never raise and never influence the gate's verdict.
    """
    try:
        sys.stderr.write(detail if detail.endswith("\n") else detail + "\n")
    except Exception:  # noqa: BLE001 — a closed stderr must not kill the gate
        pass
    try:
        folder = Path(data_dir) if data_dir else _hermes_home() / "plugin-data" / "ambient_watch"
        folder.mkdir(parents=True, exist_ok=True)
        path = folder / ERROR_LOG_NAME
        try:
            if path.stat().st_size > ERROR_LOG_MAX_BYTES:
                os.replace(path, path.with_suffix(path.suffix + ".1"))
        except OSError:
            pass
        stamp = time.strftime("%Y-%m-%dT%H:%M:%S")
        with path.open("a", encoding="utf-8") as handle:
            handle.write(f"[{stamp}] gate: {detail.strip()}\n")
        return path
    except Exception:  # noqa: BLE001 — breadcrumbs are never load-bearing
        return None


def purge_untrusted_artifacts(cfg=None, data_dir=None) -> int:
    """Delete any on-disk artifact that ever held verbatim channel text.

    Called at the top of every gate run (including silent ones) and at
    plugin registration, so a stale payload cannot outlive its sweep and
    the file sitting on a deployed machine today goes away by itself.
    Best effort: it must never raise and never influence the verdict.
    """
    removed = 0
    try:
        folder = Path(data_dir) if data_dir is not None else getattr(cfg, "data_dir", None)
        if folder is None:
            return 0
        folder = Path(folder)
        for name in UNTRUSTED_ARTIFACTS:
            try:
                (folder / name).unlink()
                removed += 1
            except FileNotFoundError:
                pass
            except OSError:
                pass
    except Exception:  # noqa: BLE001 — purging is never load-bearing
        return removed
    return removed


def install_gate(hermes_home=None) -> Path:
    """Write the path-jailed cron shim into HERMES_HOME/scripts. Idempotent."""
    home = Path(hermes_home) if hermes_home else _hermes_home()
    scripts = home / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    shim = scripts / "ambient_watch_gate.py"
    plugin_dir = str(Path(__file__).resolve().parent)
    content = _SHIM_HEADER + _SHIM_BODY.replace("__PLUGIN_DIR__", repr(plugin_dir))
    if not shim.exists() or shim.read_text(encoding="utf-8") != content:
        shim.write_text(content, encoding="utf-8")
    return shim


def _split_usage(total: int, parts: int) -> list:
    """Attribute one batched call's tokens across the channels it judged."""
    if parts <= 0:
        return []
    base, extra = divmod(int(total or 0), parts)
    return [base + (1 if i < extra else 0) for i in range(parts)]


def run_gate(cfg, store, now: float | None = None, judge_fn=None, transport=None) -> str:
    now = time.time() if now is None else now
    lines: list = []
    reportable = False  # True -> stdout is delivered to the ops channel
    # FIRST, before any early return: a payload must never outlive the sweep
    # that produced it. The incident quoted an excerpt from an EARLIER run.
    purge_untrusted_artifacts(cfg)
    try:
        if store.kill_switch():
            lines.append("ambient-watch: kill switch is ON")
            lines.append(WAKE_FALSE)
            return "\n".join(lines)

        pruned = store.prune(now, cfg.retention_days)
        if pruned:
            lines.append(f"ambient-watch: pruned {pruned} expired row(s)")

        try:
            from . import aw_budget, aw_detectors, aw_judge, aw_post
        except ImportError:
            import aw_budget
            import aw_detectors
            import aw_judge
            import aw_post

        nominees = aw_detectors.find_candidates(store, cfg, now)
        if not nominees:
            lines.append("ambient-watch: no candidates")
            lines.append(WAKE_FALSE)
            return "\n".join(lines)

        budget = aw_budget.Budget(store, cfg.budget_cfg())

        # ---- spend gate BEFORE any judgment ---------------------------
        # Claude Tag declines work over cap rather than truncating it, and a
        # declined candidate must cost nothing at all — so this runs before
        # a single token is spent.
        judgeable = []
        for cand in nominees:
            verdict = budget.decision(cand.channel, now)
            if verdict in ("exceeded", "unconfigured"):
                why = (
                    "spend cap reached"
                    if verdict == "exceeded"
                    else "no spend cap configured"
                )
                lines.append(
                    f"ambient-watch: DECLINED {cand.channel}/{cand.thread_ts} "
                    f"[{cand.kind}] -- {why} (not judged, not posted)"
                )
                # NOT record_judgment: nothing was judged, so the re-judge
                # watermark must not be consumed. A cap resets the next day and
                # an unconfigured budget gets configured — the thread has to
                # still be eligible when that happens.
                store.record_decline(
                    cand.channel, cand.thread_ts, f"declined-{verdict}",
                    excerpt=cand.excerpt, now=now,
                )
                if verdict == "unconfigured":
                    # Loud, but once a day: an unconfigured budget means
                    # ambient is silently doing nothing at all, which must not
                    # be indistinguishable from a quiet week. The breadcrumb is
                    # rate-limited with the ops line for the same reason: a
                    # known misconfiguration writing one line per tick would
                    # rotate real crash evidence out of gate_errors.log.
                    if budget.take_config_alert(now):
                        record_gate_error(
                            "budget has no cap configured (daily_usd_global / "
                            "daily_usd_per_channel / monthly_usd_global all zero) - "
                            "declining every candidate rather than spending "
                            "unbounded money on a schedule",
                            data_dir=getattr(cfg, "data_dir", None),
                        )
                        reportable = True
                        lines.append(
                            "ambient-watch: MISCONFIGURED -- no spend cap is set, so "
                            "every candidate is being declined and ambient mode is "
                            "doing nothing. Set daily_usd_per_channel and "
                            "daily_usd_global in the plugin config."
                        )
                continue
            judgeable.append(cand)

        if judgeable:
            judge = judge_fn or aw_judge.judge
            result = judge(judgeable, cfg)

            # Record spend from the judge's OWN reported usage, split across
            # the channels it judged. Exact, synchronous, no hook.
            channels = sorted({c.channel for c in judgeable})
            p_split = _split_usage(result.prompt_tokens, len(channels))
            c_split = _split_usage(result.completion_tokens, len(channels))
            for i, channel in enumerate(channels):
                if p_split[i] or c_split[i]:
                    budget.record_usage(
                        channel, result.model, p_split[i], c_split[i], now=now
                    )

            if result.error:
                # Detail goes to the breadcrumb, not to stdout: a provider
                # error string is neither ours nor safe to publish.
                charged = ""
                if getattr(result, "estimated", False):
                    # Say so explicitly: the ledger moved without a post, and
                    # an operator reading spend must know that a failing
                    # provider still costs money (it billed for a prompt it
                    # never answered) and that the figure is an estimate.
                    charged = (
                        f" [charged ~{result.prompt_tokens} ESTIMATED prompt "
                        f"tokens: the provider reported no usage]"
                    )
                record_gate_error(
                    f"judge unavailable, staying silent: {result.error}{charged}",
                    data_dir=getattr(cfg, "data_dir", None),
                )
                lines.append(
                    "ambient-watch: judge unavailable -- staying silent "
                    "(see gate_errors.log)"
                )

            by_thread = {(c.channel, c.thread_ts): c for c in judgeable}
            for verdict in result.verdicts:
                cand = by_thread.get((verdict.channel, verdict.thread_ts))
                if cand is None:
                    continue  # not a thread this sweep nominated
                store.record_judgment(
                    cand.channel, cand.thread_ts,
                    "post" if verdict.should_post else "skip",
                    confidence=verdict.confidence, reason=verdict.reason,
                    nudge=verdict.nudge, excerpt=cand.excerpt,
                    last_activity_seen=cand.last_activity, now=now,
                )
                if not verdict.should_post:
                    lines.append(
                        f"ambient-watch: withheld {cand.channel}/{cand.thread_ts} "
                        f"[{cand.kind}] conf={verdict.confidence:.2f} (judge said no)"
                    )
                    continue
                if verdict.confidence < cfg.judge_confidence_threshold:
                    lines.append(
                        f"ambient-watch: withheld {cand.channel}/{cand.thread_ts} "
                        f"[{cand.kind}] conf={verdict.confidence:.2f} "
                        f"(below {cfg.judge_confidence_threshold})"
                    )
                    continue

                if cfg.mode == "live":
                    res = aw_post.post_nudge(
                        cfg, store, cand, verdict.nudge, transport
                    )
                    reportable = True
                    if res.posted:
                        lines.append(
                            f"ambient-watch: POSTED to {cand.channel}/"
                            f"{cand.thread_ts} [{cand.kind}]: {verdict.nudge}"
                        )
                    else:
                        record_gate_error(
                            f"post failed for {cand.channel}/{cand.thread_ts}: "
                            f"{res.reason}",
                            data_dir=getattr(cfg, "data_dir", None),
                        )
                        lines.append(
                            f"ambient-watch: POST FAILED for {cand.channel}/"
                            f"{cand.thread_ts} [{cand.kind}]: {res.reason}"
                        )
                else:
                    # Shadow: judge and pay, never post. The digest is the
                    # product being soaked.
                    store.mark_shadow_seen(cand.channel, cand.thread_ts, now=now)
                    reportable = True
                    lines.append(
                        f"WOULD HAVE POSTED to {cand.channel}/{cand.thread_ts} "
                        f"[{cand.kind}]: {verdict.nudge}"
                    )

            for channel in channels:
                fired = budget.take_pending_alert(channel, now=now)
                if fired is not None:
                    reportable = True
                    lines.append(
                        f"ambient-watch: BUDGET ALERT -- {channel} crossed "
                        f"{fired:.0%} of a spend cap"
                    )

        if not reportable:
            # Nothing an operator needs to see: keep the tick free and silent.
            lines.append(WAKE_FALSE)
        return "\n".join(lines)
    except Exception as exc:  # noqa: BLE001 — fail closed, never post on error
        # This message is discarded downstream (silent runs drop stdout), so
        # the breadcrumb is the only durable evidence a dead gate leaves.
        record_gate_error(
            f"run_gate failed ({type(exc).__name__}), failing closed\n"
            + traceback.format_exc(),
            data_dir=getattr(cfg, "data_dir", None),
        )
        return "\n".join(
            [f"ambient-watch: gate error ({type(exc).__name__}), failing closed",
             WAKE_FALSE]
        )


def main(argv: list[str]) -> int:
    # The audit line can contain a model-authored nudge, and a watched channel
    # may not be English. On Windows a cron subprocess can inherit a cp1252
    # stdout, where one non-ASCII character in the nudge would raise
    # UnicodeEncodeError -> non-zero exit -> cron delivers "script failed"
    # every tick. Force UTF-8 with replacement instead.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:  # noqa: BLE001 — older/odd streams: keep going
        pass

    try:
        from .aw_config import load_config
        from .aw_store import AmbientStore
    except ImportError:
        from aw_config import load_config
        from aw_store import AmbientStore

    cfg = load_config()
    store = AmbientStore(cfg.data_dir / "ambient.db")
    try:
        if len(argv) >= 2 and argv[0] == "--kill":
            store.set_kill_switch(argv[1].lower() in ("on", "1", "true"))
            print(f"ambient-watch kill switch: {argv[1]}")
            return 0
        print(run_gate(cfg, store))
        return 0
    finally:
        store.close()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
